ballots/urls.py
"""Polls URL configuration.
"""

from django.urls import path

from . import views

app_name = 'ballots'
urlpatterns = [
    path('', views.home, name='home'),
    path('new/', views.new, name='new'),
    path('edit/<int:ballot_id>/', views.edit, name='edit'),
    path('delete/<int:ballot_id>/', views.delete, name='delete'),
    path('ballot/<int:ballot_id>/', views.ballot, name='ballot'),
    path('retract_vote/<int:ballot_id>/', views.retract_vote, name='retract_vote'),
    path('markdownify/', views.markdownify, name='markdownify'),
]

team/urls.py
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from team import settings

urlpatterns = [
    path('', include('people.root_urls', namespace='root')),
    path('people/', include('people.urls', namespace='people')),
    path('admin/', admin.site.urls),
    path('ballots/', include('ballots.urls', namespace='ballots')),
    path('skills/', include('skills.urls', namespace='skills')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ballots/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from people.models import Person, Level


class Ballot(models.Model):
    # Who has created this ballot.
    creator = models.ForeignKey(Person, on_delete=models.PROTECT)
    # The essence of the ballot.
    question = models.CharField(max_length=100)
    # The details.
    description = models.TextField()
    # Minimal level required to see this ballot and vote in it.
    access_level = models.ForeignKey(Level, on_delete=models.PROTECT)
    # Whether this ballot is open, i.e., voters can see votes of others before casting their own vote.
    open = models.BooleanField(default=True)
    # Whether this ballot is active, i.e., the creator has pushed the Publish button, and people can see it and vote.
    active = models.BooleanField(default=False)
    # When this ballot has been created.
    created = models.DateTimeField()
    # When this ballot should end.
    deadline = models.DateTimeField()
    # Whether the ballot is over and should no longer be displayed to people.
    archived = models.BooleanField(default=False)

    class Meta:
        verbose_name = _('Ballot')
        verbose_name_plural = _('Ballots')

    def __str__(self):
        return '{date} by {author}: {title}'.format(date=self.created, author=self.creator, title=self.question)

    @property
    def overdue(self):
        return self.deadline >= timezone.now()


class Vote(models.Model):
    VOTE_YES = 'Y'
    VOTE_NO = 'N'
    VOTE_ABSTAIN = 'A'
    VOTE_LEAVE = 'L'
    VOTE_CHOICES = (
        (VOTE_YES, _('Yes')),
        (VOTE_NO, _('No')),
        (VOTE_ABSTAIN, _('Abstain')),
        (VOTE_LEAVE, _('On Leave')),
    )

    ballot = models.ForeignKey(Ballot, on_delete=models.CASCADE)
    caster = models.ForeignKey(Person, on_delete=models.PROTECT)
    vote = models.CharField(choices=VOTE_CHOICES, max_length=1)
    comment = models.TextField(blank=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=('caster', 'ballot'), name='one_vote_per_ballot'),
        ]
        verbose_name = _('Vote')
        verbose_name_plural = _('Votes')

    @property
    def vote_as_string(self):
        for choice in Vote.VOTE_CHOICES:
            if self.vote == choice[0]:
                return choice[1]
        return _('UNKNOWN')

ballots/forms.py
from django import forms

from people.models import Level
from .models import Vote, Ballot


class BallotForm(forms.ModelForm):
    """Creates or edits the ballot.

    This form is used by the ballots.views.new().
    """

    class Meta:
        model = Ballot
        fields = ('question', 'description', 'access_level', 'open', 'deadline')

    def __init__(self, *args, **kwargs):
        max_level = kwargs.pop('max_level')
        assert max_level >= 1, "The access level must not be less than 1!"

        super(BallotForm, self).__init__(*args, **kwargs)

        if max_level == 1:
            self.fields.pop('access_level')
        else:
            self.fields['access_level'].choices = ((l.pk, l.name) for l in
                                                   Level.objects.filter(value__lte=max_level).order_by('value'))

        self.fields['open'] = forms.ChoiceField(choices=((True, 'Open'), (False, 'Secret')), widget=forms.Select())


class VoteForm(forms.ModelForm):
    """Records vote in a ballot.

    This form is used by the ballots.views.ballot().
    """

    class Meta:
        model = Vote
        fields = ('vote', 'comment')

ballots/views.py
import collections

from django.http.response import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone

from common.auth import get_user_login
from people.models import Person, Level
from ballots.forms import VoteForm, BallotForm
from ballots.models import Ballot, Vote


def get_user(request):
    # Take the login from the basic auth header.
    user_login = get_user_login(request)

    try:
        return Person.objects.get(login=user_login)
    except Person.DoesNotExist:
        raise Http404('User does not exist')


def home(request):
    """Shows the ballots available to the current user.
    """

    user = get_user(request)

    ballots = [b for b in
               Ballot.objects.filter(access_level__value__lte=user.level.value, archived=False).order_by('-deadline')]
    votes = Vote.objects.filter(ballot__in=ballots, caster=user)
    votes_index = {v.ballot.pk: v for v in votes}

    ballots_to_vote = []
    active_ballots = []
    for ballot in ballots:
        if ballot.pk in votes_index:
            active_ballots.append({'ballot': ballot, 'vote': votes_index[ballot.pk]})
        else:
            ballots_to_vote.append(ballot)

    return render(request,
                  'ballots/home.html',
                  {'page_title': 'Our ballots',
                   'ballots_to_vote': ballots_to_vote,
                   'active_ballots': active_ballots,
                   'user': user})


def new(request):
    user = get_user(request)

    form = BallotForm(request.POST or None, max_level=user.level.value)
    if request.method == 'POST' and form.is_valid():
        new_ballot = Ballot(creator=user,
                            question=form.cleaned_data['question'],
                            description=form.cleaned_data['description'],
                            access_level=form.cleaned_data['access_level'],
                            open=form.cleaned_data['open'],
                            created=timezone.now(),
                            deadline=form.cleaned_data['deadline'])
        new_ballot.save()
        return HttpResponseRedirect(reverse('ballots:ballot', kwargs={'ballot_id': new_ballot.pk}))
    return render(request,
                  'ballots/new_or_edit.html',
                  {'page_title': 'New ballot',
                   'form': form,
                   'user': user})


def edit(request, ballot_id):
    user = get_user(request)

    try:
        ballot = Ballot.objects.get(pk=ballot_id)
    except Ballot.DoesNotExist:
        raise Http404('Ballot does not exist')

    if user != ballot.creator:
        # This is not our ballot; cannot edit.
        return HttpResponseRedirect(reverse('ballots:ballot', kwargs={'ballot_id': ballot.pk}))

    form = BallotForm(request.POST or None, max_level=user.level.value, instance=ballot)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('ballots:ballot', kwargs={'ballot_id': ballot.pk}))

    return render(request,
                  'ballots/new_or_edit.html',
                  {'page_title': 'New ballot',
                   'form': form,
                   'user': user})


def delete(request, ballot_id):
    user = get_user(request)

    try:
        ballot = Ballot.objects.get(pk=ballot_id)
    except Ballot.DoesNotExist:
        raise Http404('Ballot does not exist')

    if user != ballot.creator:
        raise Exception('This is not your ballot')

    ballot.delete()

    return HttpResponseRedirect(reverse('ballots:home'))


def ballot(request, ballot_id):
    """Shows details for the single skill.
    """

    try:
        ballot = Ballot.objects.get(pk=ballot_id)
    except Ballot.DoesNotExist:
        raise Http404('Ballot does not exist')

    user = get_user(request)
    if user.level.value < ballot.access_level.value:
        raise Http404('Ballot does not exist')

    finished = timezone.now() >= ballot.deadline

    if not finished and request.method == 'POST':
        form = VoteForm(request.POST)
        if not form.is_valid():
            # Our form doesn't have fields that could contain invalid values, so if we are here, something is seriously
            # broken.  Terminate.
            raise Exception('Oops')

        vote = Vote(ballot=ballot, caster=user, vote=form.cleaned_data['vote'], comment=form.cleaned_data['comment'])
        vote.save()

        return HttpResponseRedirect(reverse('ballots:ballot', kwargs={'ballot_id': ballot_id}))

    our_vote = None
    form = None
    try:
        our_vote = Vote.objects.get(ballot=ballot, caster=user)
    except Vote.DoesNotExist:
        form = VoteForm()

    pending = []
    if ballot.open or finished:
        votes = [v for v in Vote.objects.filter(ballot=ballot)]
        vote_count = len(votes)
        votes_index = {v.caster.pk: v for v in votes}
        people = [p for p in Person.objects.filter(level__value__gte=ballot.access_level.value)]
        people_count = len(people)
        votes = collections.defaultdict(list)
        comments = collections.defaultdict(list)
        for person in people:
            if person.pk not in votes_index:
                pending.append(person.login)
                continue
            v = votes_index[person.pk]
            votes[v.vote].append(person.login)
            if v.comment:
                comments[v.vote].append({'person': person, 'comment': v.comment})
        ballot_data = {vote: {'count': len(votes[vote]),
                              'share': int(100 * len(votes[vote]) / people_count),
                              'people': ', '.join(sorted(votes[vote], key=str.casefold)),
                              'comments': sorted(comments[vote], key=lambda c: c['person'].login.lower())}
                       for vote, _ in Vote.VOTE_CHOICES}

        titles = {c: v for (c, v) in Vote.VOTE_CHOICES}
        all_votes = [{'code': code,
                      'title': titles[code], 'votes': ballot_data[code],
                      'bar_length': int(80 * ballot_data[code]['count'] / people_count)}
                     for code in ('Y', 'N', 'A')]
    else:
        all_votes = None
        vote_count = 0
        people_count = 0

    return render(request,
                  'ballots/ballot.html',
                  {'page_title': 'ballot: {}'.format(ballot.question),
                   'ballot': ballot,
                   'finished': finished,
                   'show_edit': ballot.creator == user,
                   'our_vote': our_vote,
                   'form': form if not finished else None,
                   'all_votes': all_votes,
                   'vote_count': vote_count,
                   'people_count': people_count,
                   'pending': {
                       'count': len(pending),
                       'people': ', '.join(sorted(pending, key=str.casefold)) if len(pending) > 1 else pending,
                   },
                   'user': user})


def retract_vote(request, ballot_id):
    """Erases the user's existing vote.
    """

    try:
        ballot = Ballot.objects.get(pk=ballot_id)
    except Ballot.DoesNotExist:
        raise Http404('Ballot does not exist')

    user = get_user(request)
    if user.level.value < ballot.access_level.value:
        raise Http404('Ballot does not exist')

    if timezone.now() < ballot.deadline:
        try:
            our_vote = Vote.objects.get(ballot=ballot, caster=user)
            our_vote.delete()
        except Vote.DoesNotExist:
            pass

    return HttpResponseRedirect(reverse('ballots:ballot', kwargs={'ballot_id': ballot_id}))


def markdownify(request):
    return render(request,
                  'ballots/markdownify.html',
                  {'text': request.POST.get('text', '')})

ballots/templates/ballots/ballot.html
{% extends "ballots/base.html" %}
{% load static %}{% load markdownify %}

{% block content %}
<h1><a href="{% url 'ballots:home' %}">Our ballots</a> &rarr; {{ ballot.question }}</h1>

<p>Created at {{ ballot.created }} by {{ ballot.creator }}.  Deadline: {{ ballot.deadline }}.{% if show_edit %}  <a href="{% url 'ballots:edit' ballot.pk %}">Edit</a>.{% endif %}</p>

<hr>

{{ ballot.description|markdownify }}

<hr>

{% if form and not finished %}
<p>Please cast your vote, {{ user.login }}.</p>

<form method="post">
    {% csrf_token %}
    <div class="t-row">
        <div class="t-cell ballots-vote-form-label">
            Vote:
        </div>
        <div class="t-cell ballots-vote-form-vote">
            <label><input type="radio" name="vote" required value="Y">Yes</label>
        </div>
        <div class="t-cell ballots-vote-form-vote">
            <label><input type="radio" name="vote" required value="N">No</label>
        </div>
        <div class="t-cell ballots-vote-form-vote">
            <label><input type="radio" name="vote" required value="A">Abstain</label>
        </div>
    </div>
    <div class="t-row">
        <div class="t-cell ballots-vote-form-label">
            Comment (optional):
        </div>
        <div class="t-cell ballots-vote-form-comment">
            {{ form.comment }}
        </div>
    </div>
    <div><button type="submit">Submit</button></div>
</form>
{% endif %}

{% if our_vote %}
    <h2>You voted {{ our_vote.vote_as_string }}</h2>
    {% if finished %}
        <p>Tnis ballot has ended.  You can no longer change your mind.</p>
    {% else %}
        <p>Changed your mind? <a href="{% url 'ballots:retract_vote' ballot.pk %}" onclick="return confirm('This will erase your current choice and your comment, if any, and you will need to vote again. Continue?');">Retract the vote</a>.</p>
    {% endif %}
{% endif %}

{% if ballot.open or finished %}
    <h2>Ballot status</h2>
    <p>{{ vote_count }} of {{ people_count }} people have voted.</p>
    {% for group in all_votes %}
        <div class="t-row">
            <div class="t-cell ballots-votes-{{ group.code }}" style="width: {{ group.bar_length }}%">&nbsp;</div>
            <div class="t-cell">{{ group.title }}: {{ group.votes.count }} ({{ group.votes.share }}%)</div>
        </div>
    {% endfor %}

    <div class="t-row">
        {% for group in all_votes %}
            <div class="t-cell ballots-vote-group">
                <h3>{{ group.title }}: {{ group.votes.count }}</h3>
                {{ group.votes.people }}
                {% if group.votes.comments %}
                    <ul>
                        {% for comment in group.votes.comments %}
                            <li>{{ comment.person.login }}: {{ comment.comment }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        {% endfor %}
    </div>

    {% if pending.count %}
        <h3>Not voted: {{ pending.count }}</h3>
        <p>{{ pending.people }}</p>
    {% endif %}
{% else %}
    <p>This ballot is secret.  You cannot see others' votes until the ballot is complete.</p>
{% endif %}

{% endblock %}

ballots/templates/ballots/base.html
{% extends "base.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'ballots/style.css' %}">
{% endblock %}

ballots/templates/ballots/home.html
{% extends "ballots/base.html" %}
{% load static %}

{% block content %}
<h1>Our ballots</h1>

<p><a href="{% url 'ballots:new' %}">Create a new ballot</a></p>

{% if ballots_to_vote %}
    <h2>Ballots for you to vote, {{ user.login }}</h2>
    {% for ballot in ballots_to_vote %}
        <p><a href="{% url 'ballots:ballot' ballot.pk %}">{{ ballot.question }}</a></p>
    {% endfor %}
{% endif %}

{% if active_ballots %}
    <h2>Active ballots that you have already voted in</h2>
    {% for b in active_ballots %}
        <p><a href="{% url 'ballots:ballot' b.ballot.pk %}">{{ b.ballot.question }}</a> <strong>{{ b.vote.vote_as_string }}</strong></p>
    {% endfor %}
{% endif %}

{% endblock %}

ballots/templates/ballots/markdownify.html
{% load static %}{% load markdownify %}

{{ text|markdownify }}

ballots/templates/ballots/new.html
{% extends "ballots/base.html" %}
{% load static %}

{% block content %}
<h1><a href="{% url 'ballots:home' %}">Our ballots</a> &rarr; {% if form.instance.pk %}Edit{% else %}New{% endif %} ballot</h1>

<form method="post">
    {% csrf_token %}
    <div class="t-row">
        <div class="t-cell ballots-edit-form-label">Question:</div>
        <div class="t-cell ballots-edit-form-field">{{ form.question }}</div>
    </div>
    <div class="t-row">
        <div class="t-cell ballots-edit-form-label">Description:</div>
        <div class="t-cell ballots-edit-form-field" id="description">{{ form.description }}</div>
    </div>
    <div class="t-row">
        <div class="t-cell ballots-edit-form-label"></div>
        <div class="t-cell ballots-edit-form-field ballots-edit-form-description-preview" id="description-preview">
            {{ form.description.value }}
        </div>
    </div>
    <div class="t-row">
        <div class="t-cell ballots-edit-form-label">Settings:</div>
        <div class="t-cell ballots-edit-form-field">
            <div class="t-row">
                <div class="t-cell">Deadline:</div>
                <div class="t-cell">{{ form.deadline }}{{ form.deadline.errors }}</div>
                <div class="t-cell">Type:</div>
                <div class="t-cell">{{ form.open }}</div>
                <div class="t-cell">Access:</div>
                <div class="t-cell">{{ form.access_level }}</div>
            </div>
        </div>
    </div>
    <hr>
    <div>
        <button type="submit">{% if form.instance.pk %}Update{% else %}Create{% endif %}</button>
    </div>
</form>

<script language="JavaScript">
var updateRequest = null;
var repeatRequest = false;

function getPreview(text) {
    let data = new FormData();
    data.append('text', text);;
    data.append('csrfmiddlewaretoken', '{{ csrf_token }}');

    fetch('{% url 'ballots:markdownify' %}', {
        method: 'POST',
        mode: 'same-origin',
        cache: 'no-cache',
        credentials: 'same-origin',
        redirect: 'error',
        referrerPolicy: 'same-origin',
        body: data
    }).then(response => response.text())
      .then(data => {
        document.getElementById("description-preview").innerHTML = data;
        if (repeatRequest) {
            repeatRequest = false;
            updateRequest = setTimeout(getPreview, 3000, document.getElementById("id_description").value);
        } else {
            updateRequest = null;
        }
    });
}

window.onload = function() {
    document.getElementById("id_description").addEventListener("input", function(e) {
        var textarea = e.target;
        if (textarea.scrollHeight > textarea.clientHeight) {
            textarea.style.height = textarea.scrollHeight + 10 + "px";
        }

        if (updateRequest === null)
            updateRequest = setTimeout(getPreview, 3000, textarea.value);
        else
            repeatRequest = true;
    })
};



</script>

{% endblock %}

ballots/templates/ballots/new_or_edit.html
{% extends "ballots/base.html" %}
{% load markdownify %}{% load static %}

{% block content %}
<h1><a href="{% url 'ballots:home' %}">Our ballots</a> &rarr; {% if form.instance.pk %}Edit{% else %}New{% endif %} ballot</h1>

<form method="post">
    {% csrf_token %}
    <div class="t-row">
        <div class="t-cell ballots-edit-form-label">Question:</div>
        <div class="t-cell ballots-edit-form-field">{{ form.question }}</div>
    </div>
    <div class="t-row">
        <div class="t-cell ballots-edit-form-label">Description:</div>
        <div class="t-cell ballots-edit-form-field" id="description">{{ form.description }}</div>
    </div>
    <div class="t-row">
        <div class="t-cell ballots-edit-form-label"></div>
        <div class="t-cell ballots-edit-form-field ballots-edit-form-description-preview" id="description-preview">
            {% if form.description.value %}
                {{ form.description.value|markdownify }}
            {% endif %}
        </div>
    </div>
    <div class="t-row">
        <div class="t-cell ballots-edit-form-label">Settings:</div>
        <div class="t-cell ballots-edit-form-field">
            <div class="t-row">
                <div class="t-cell">Deadline:</div>
                <div class="t-cell">{{ form.deadline }}{{ form.deadline.errors }}</div>
                <div class="t-cell">Type:</div>
                <div class="t-cell">{{ form.open }}</div>
                <div class="t-cell">Access:</div>
                <div class="t-cell">{{ form.access_level }}</div>
            </div>
        </div>
    </div>
    <hr>
    <div class="t-row">
        <div class="t-cell">
            <button type="submit">{% if form.instance.pk %}Update{% else %}Create{% endif %}</button>
        </div>
    </div>
</form>

<script language="JavaScript">
var updateRequest = null;
var repeatRequest = false;

function getPreview(text) {
    let data = new FormData();
    data.append('text', text);;
    data.append('csrfmiddlewaretoken', '{{ csrf_token }}');

    fetch('{% url 'ballots:markdownify' %}', {
        method: 'POST',
        mode: 'same-origin',
        cache: 'no-cache',
        credentials: 'same-origin',
        redirect: 'error',
        referrerPolicy: 'same-origin',
        body: data
    }).then(response => response.text())
      .then(data => {
        document.getElementById("description-preview").innerHTML = data;
        if (repeatRequest) {
            repeatRequest = false;
            updateRequest = setTimeout(getPreview, 3000, document.getElementById("id_description").value);
        } else {
            updateRequest = null;
        }
    });
}

function updateHeight(textarea) {
    if (textarea.scrollHeight > textarea.clientHeight) {
        textarea.style.height = textarea.scrollHeight + 10 + "px";
    }
}

window.onload = function() {
    document.getElementById("id_description").addEventListener("input", function(e) {
        var textarea = e.target;
        updateHeight(textarea);

        if (updateRequest === null)
            updateRequest = setTimeout(getPreview, 3000, textarea.value);
        else
            repeatRequest = true;
    })

    updateHeight(document.getElementById("id_description"));
};
</script>

{% endblock %}