people/urls.py
"""URL configuration of the People application.

This is the main section for the URL map. See also `.root_urls.py`.
"""

from django.http.response import HttpResponseRedirect
from django.urls import path, reverse

from common.auth import get_user_login
from . import views


def home(request):
    return HttpResponseRedirect(reverse('root:person', args=[get_user_login(request)]))


app_name = 'people'
urlpatterns = [
    # Convenience view that redirects to one of meaningful URLs.
    path('', home, name='home'),

    # New contribution form.  The new contribution will be created for the user that is currently logged in.
    path('contribution/new/', views.new_contribution, name='contribution-new'),
    # Shows a single contribution, and allows editing it if it belongs to the user that is currently logged in.
    path('contribution/<int:contribution_id>/', views.render_contribution, name='contribution'),
    # Shows contributions of a person with `login`.
    path('contributions/<str:login>/', views.render_contributions, name='contributions'),

    # Sets the current team (stores it in the session).
    path('<str:login>', views.render_person, name='person'),
    # People picker.
    path('picker/', views.picker, name='picker'),

    # Shows details of a single team.
    path('team/<str:team_slug>/', views.render_team, name='team'),
    # Shows all teams.
    path('teams/', views.render_teams, name='teams'),
]

skills/urls.py
"""skills URL configuration.
"""

from django.urls import path

from . import views

app_name = 'skills'
urlpatterns = [
    # Convenience view that redirects to one of meaningful URLs.
    path('', views.home, name='home'),
    # Sets the current team (stores it in the session).
    # Recognises two special values for 1) showing data for all teams and 2) resetting the view to the teams of the
    # current user.
    path('set-current-team/<str:team_slug>/', views.set_current_team, name='set-current-team'),

    # Team diagrams show data for the teams of the current user.  That requires the user to be in some (at least one)
    # team.  If that is not the case, these views redirect to the team picker.

    # Team diagram of interest versus knowledge.
    path('interest-vs-knowledge/', views.interest_vs_knowledge, name='interest-vs-knowledge'),
    # Team diagram of market demand versus knowledge and interest.
    path('demand-vs-knowledge/', views.demand_vs_knowledge, name='demand-vs-knowledge'),
    # Team portfolio (list of all projects and their focus).
    path('projects/', views.projects, name='projects'),
    # New project form.
    path('project-new/', views.project_new, name='project-new'),
    # Self-assessment form.
    path('self-assess/', views.self_assess, name='self-assess'),

    # Wrapper for the views in the above group.  Shows the team selection form if the current user is not listed in any.
    path('pick-teams/', views.render_pick_teams, name='pick-teams'),

    # Views that do not require the user to be in any team.

    # Shows a single project.  Optionally allows editing it.
    path('project/<int:project_id>/', views.project, name='project'),
    # Shows skills of a single person.
    path('person/<str:login>/', views.render_person, name='person'),
    # Shows data for a single skill: who knows it, and who is interested in it.
    path('skill/<int:skill_id>/', views.render_skill, name='skill'),

    # Team diagram of interest versus knowledge for the particular team, or for all teams.
    path('interest-vs-knowledge/<str:team_slug>/', views.interest_vs_knowledge_for_team,
         name='interest-vs-knowledge-for-team'),
    # Team diagram of market demand versus  knowledge and interest for the particular team.
    path('demand-vs-knowledge/<str:team_slug>/', views.demand_vs_knowledge_for_team,
         name='demand-vs-knowledge-for-team'),
    # Team portfolio (list of all projects and their focus) for the particular team.
    path('projects/<str:team_slug>/', views.projects_for_team, name='projects-for-team'),
]

team/urls.py
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from team import settings

urlpatterns = [
    path('', include('people.root_urls', namespace='root')),
    path('people/', include('people.urls', namespace='people')),
    path('admin/', admin.site.urls),
    path('ballots/', include('ballots.urls', namespace='ballots')),
    path('skills/', include('skills.urls', namespace='skills')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

people/models.py
import datetime
import os
from uuid import uuid4

from django.db import models
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _

from team import settings


def mangle_filename(instance, filename):
    """Generates a UUID-based unique hard-to-guess filename

    :param instance: the DB model that this path is generated for
    :param filename: the "original" filename (normally comes from the uploaded file)
    :return: path to the new location within `MEDIA_ROOT`

    The `instance` may have a `STORAGE_PATH` attribute that will be used as a prefix of the resulting path
    """
    name, ext = os.path.splitext(filename)
    new_path = os.path.join(instance.STORAGE_PATH if hasattr(instance, "STORAGE_PATH") else "",
                            '{}{}'.format(uuid4().hex, ext))
    # UUID is generated based on current time and 14 bit random component as parts, so the collision is not likely.
    # In an unlikely event of the collision, just bail out.
    assert not os.path.exists(new_path)
    return new_path


class Level(models.Model):
    name = models.CharField(max_length=20)
    value = models.IntegerField(unique=True)

    class Meta:
        verbose_name = _('Level')
        verbose_name_plural = _('Levels')

    def __str__(self):
        return self.name


class Person(models.Model):
    # Unique ID of the person in the system.
    login = models.CharField(max_length=30, unique=True)
    # Full name.
    full_name = models.CharField(max_length=100, null=True)
    # Date when this person joined the company.
    join_date = models.DateField(null=True)
    # Level in the company hierarchy.
    level = models.ForeignKey(Level, on_delete=models.PROTECT, null=True)

    teams = models.ManyToManyField('Team', blank=True)

    class Meta:
        verbose_name = _('Person')
        verbose_name_plural = _('People')

    def __str__(self):
        return '{login}@ {name}'.format(login=self.login, name=self.full_name)


class PersonalData(models.Model):
    """
    Extended data about a person.
    """

    STORAGE_PATH = settings.PEOPLE_PERSONAL_DATA_STORAGE

    # Extends the Person model.
    person = models.OneToOneField(Person, on_delete=models.CASCADE)
    # Geographical location in form of a query for the external locator service, like "London, United Kingdom".
    location_query = models.CharField(max_length=100, null=True, blank=True)
    # Timezone database name, like "Europe/Madrid".
    tz_name = models.CharField(max_length=30, default="Etc/UTC")
    # Typical hour of beginning the work.
    work_begin_time = models.TimeField(default=datetime.time(9, 00))
    # Typical hour of ending the work.
    work_end_time = models.TimeField(default=datetime.time(18, 00))
    # Person's avatar.
    avatar = models.ImageField(null=True, blank=True, upload_to=mangle_filename)

    class Meta:
        verbose_name = _('Personal data')
        verbose_name_plural = _('Personal data')

    def __str__(self):
        return str(self.person)


# noinspection PyUnusedLocal
@receiver(models.signals.pre_save, sender=PersonalData)
def delete_old_avatar(sender, instance, **kwargs):
    if not instance.pk:
        return

    try:
        old_avatar = PersonalData.objects.get(pk=instance.pk).avatar
        # old_avatar can be None if it belongs to a new PersonalData that has just been created.
        # It should be deleted IFF it exists AND the new instance differs (that is, either is empty or points to another
        # file).
        if old_avatar and old_avatar.url and old_avatar != instance.avatar:
            old_avatar.delete(save=False)
    except PersonalData.DoesNotExist:
        pass


class Team(models.Model):
    """
    Team inside a company.

    Groups various things within the company, primarily people, but not only people.

    The name may be confusing because it clashes with the name of this entire project.  Sorry.
    """

    slug = models.SlugField(max_length=50, unique=True)
    # Arbitrary name of the team; however, it has some constraints.
    name = models.CharField(max_length=50, unique=True)
    # Arbitrary text describing the team.
    description = models.TextField(default='', blank=True)

    class Meta:
        verbose_name = _('Team')
        verbose_name_plural = _('Teams')

    def __str__(self):
        return self.name

people/forms.py
from django import forms

from people.models import PersonalData
from skills.models import Contribution


class ContributionForm(forms.ModelForm):
    """Allows to edit personal contribution.

    Used by the people.add_or_edit_contribution view.
    """
    class Meta:
        model = Contribution
        fields = ('project', 'description')


class PersonalDataForm(forms.ModelForm):
    """Allows to edit personal details.

    Used by the people.render_person view.
    """
    class Meta:
        model = PersonalData
        fields = ('location_query', 'tz_name', 'work_begin_time', 'work_end_time')


class SearchForm(forms.Form):
    """Captures the login of a person to show.

    Used by the people.render_person view.
    """
    login = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Type to search'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        fields = ('login',)

skills/forms.py
from django import forms

from people.models import Team
from .models import Measurement, Project, ProjectFocusRecord


class MeasurementForm(forms.ModelForm):
    """Records levels of knowledge and interest for one skill.

    This form is used by the skills.assess view to render one line of the assessment form.
    """
    def __init__(self, *args, **kwargs):
        if 'initial' in kwargs:
            for field in ('title', 'category_title', 'separator'):
                if field in kwargs['initial']:
                    setattr(self, field, kwargs['initial'][field])
        super().__init__(*args, **kwargs)

    class Meta:
        model = Measurement
        fields = ('skill', 'knowledge', 'interest')
        widgets = {'skill': forms.HiddenInput}


class ProjectFocusRecordForm(forms.ModelForm):
    """
    Records entry of skill into the project focus.

    This form is used by the skills.assess_project view to render one line of the assessment form.
    """
    selected = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        if 'initial' in kwargs:
            for field in ('title', 'category_title'):
                if field in kwargs['initial']:
                    setattr(self, field, kwargs['initial'][field])
        super().__init__(*args, **kwargs)

    class Meta:
        model = ProjectFocusRecord
        fields = ('skill', 'selected')
        widgets = {'skill': forms.HiddenInput}


class ProjectForm(forms.ModelForm):
    """
    Records data on the project.

    This form is used by the skills.assess_project view to render the project fields.
    """
    class Meta:
        model = Project
        fields = ('name', 'description', 'active')


class PickTeamForm(forms.ModelForm):
    """
    Records selection of a team.

    This form is used by the skills.pick_teams view to render one line of the form.
    """
    selected = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        if 'initial' in kwargs:
            for field in ('id', 'name', 'team'):
                if field in kwargs['initial']:
                    setattr(self, field, kwargs['initial'][field])
        super().__init__(*args, **kwargs)

    class Meta:
        model = Team
        fields = ('selected', )

people/views.py
from django.contrib import messages
from django.db.models.functions import Lower
from django.http.response import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import resolve, Resolver404, reverse
from django.utils.translation import gettext_lazy as _

from common.auth import get_user_login
from common.forms import make_readonly
from inventory.models import Device
from skills.models import Contribution
from .forms import ContributionForm, PersonalDataForm, SearchForm
from .models import Level, Person, PersonalData, Team


def add_or_edit_contribution(request, contribution_id):
    contribution = Contribution.objects.get(pk=contribution_id) if contribution_id > 0 else None
    can_edit = (contribution.person.login == get_user_login(request)) if contribution else True
    contribution_form = ContributionForm(request.POST or None, instance=contribution)
    if not can_edit:
        make_readonly(contribution_form)

    if can_edit and request.method == "POST":
        if not contribution_form.is_valid():
            messages.warning(request, _("Please fix the data!"))
        else:
            saved_contribution = contribution_form.save()
            messages.success(request, _("Contribution saved"))
            return HttpResponseRedirect(reverse("people:contribution", args=[saved_contribution.pk]))

    try:
        return render(request, "people/contribution.html", {
            "can_edit": can_edit,
            "contribution_form": contribution_form,
            "contribution_list_title": _("My contributions") if can_edit else _(
                "{person}'s contributions".format(person=contribution.person.login)),
            "contribution_title": contribution.project.name if contribution else _("<New>"),
            "person": contribution.person if contribution else Person.objects.get(login=get_user_login(request)),
        })
    except Person.DoesNotExist:
        raise Http404("User does not exist")


def new_contribution(request):
    return add_or_edit_contribution(request, 0)


def render_contribution(request, contribution_id):
    return add_or_edit_contribution(request, contribution_id)


def render_contributions(request, login):
    try:
        person = Person.objects.get(login=login)
        contributions = Contribution.objects.filter(person=person).order_by("project__name")
        return render(request, "people/contributions.html", {
            "can_edit": (login == get_user_login(request)),
            "person": person,
            "contributions": contributions
        })

    except Person.DoesNotExist:
        raise Http404("User does not exist")


def render_person(request, login):
    people = Person.objects.order_by('login')
    search_form = SearchForm(request.POST or None)

    try:
        if request.method == 'POST' and search_form.is_valid():
            return HttpResponseRedirect(reverse('root:person', args=[search_form.cleaned_data['login']]))

        person = Person.objects.get(login=login)
        try:
            personal_data = PersonalData.objects.get(person=person)
        except PersonalData.DoesNotExist:
            personal_data = PersonalData(person=person)
            personal_data.save()

        can_edit = (login == get_user_login(request))
        if can_edit:
            personal_data_form = PersonalDataForm(request.POST or None, instance=personal_data)
            if request.method == 'POST' and personal_data_form.is_valid():
                personal_data_form.save()
                return HttpResponseRedirect(reverse('root:person', args=[login]))

        # The `at_person_view` flag is part of a hack to force "active" state for the menu item for the root:person URL.
        # Django-menu-generator does not seem to recognise that URL as "child" for the People app, and does not activate
        # the menu item as expected.  That is why we set explicit flags for these two menu items, and the templates look
        # at them when rendering the menu.
        context = {'at_person_view': True,
                   'can_edit': can_edit,
                   'inventory': Device.objects.filter(assignee=person),
                   'people': people,
                   'person': person,
                   'personal_data': personal_data,
                   'search_form': search_form}
        if can_edit:
            context['personal_data_form'] = personal_data_form

        return render(request, 'people/person.html', context)
    except Person.DoesNotExist:
        try:
            path = '/{login}/'.format(login=login)
            resolve(path)  # If this fails, it will raise Resolver404.  Otherwise we just redirect to that URL.
            return HttpResponseRedirect(path)
        except Resolver404:
            pass
        return render(request, 'people/person.html', {
            'person': None,
            'people': people,
            'search_form': search_form})


def picker(request):
    return render(request, 'people/picker.html', {
        "levels": Level.objects.order_by("id"),
        "people": Person.objects.order_by(Lower("login")),
    })


def render_team(request, team_slug):
    return render(request, "people/team.html", {
        "team": Team.objects.get(slug=team_slug),
    })


def render_teams(request):
    return render(request, "people/teams.html", {
        "teams": Team.objects.order_by("name"),
    })

skills/templates/skills/assess-done.html
{% extends "base.html" %}

{% block content %}
<h1>Thank you for your input!</h1>

<p>Your latest data is saved.  <a href="{% url 'skills:home' %}">Return to the main page</a>.</p>
{% endblock %}

skills/templates/skills/assess.html
{% extends "skills/base.html" %}
{% load static %}

{% block content %}
<h1>Self assessment of skills</h1>

<p>Hi there, {{ user_login }}.  {% if latest_assessment %}Your latest record is {{ latest_assessment.date }}.{% else %}We have no records for you.{% endif %}</p>

<form method="post">
    {% csrf_token %}
    {{ formset.management_form }}
        {% for form in formset %}
            {% for field in form.hidden_fields %}
                {{ field }}
            {% endfor %}
            {% if form.category_title %}
                <hr>
                <h2>{{ form.category_title }}</h2>
            {% endif %}
            <div class="t-row">
                <div class="t-cell skills-assess-form-label">{{ form.title }}</div>
                {% for field in form.visible_fields %}
                    <div class="t-cell skills-assess-form-field">
                        {{ field }}
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    <hr>
    <div class="t-row">
        <div class="t-cell"><button type="submit">Submit</button></div>
    </div>
</form>
{% endblock %}

skills/templates/skills/base.html
{% extends "base.html" %}
{% load static %}{% load menu_generator %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'skills/style.css' %}">
{% endblock %}

{% block second_level_menu %}
    <div class="menu-bar">
        <div class="menu">
            {% get_menu "NAV_MENU_2ND_LEVEL" as menu %}
            {% for item in menu %}
                <div class="{% if item.selected %} active {% endif %}">
                    <a href="{{ item.url }}"> <i class="{{ item.icon_class }}"></i> {{ item.name }}</a>
                </div>
            {% endfor %}
        </div>

        {% if show_team_selector %}
            <div>
                <script>
                    function selectTeam(team_slug) {
                        window.location = '{% url 'skills:set-current-team' '*' %}'.replace('*', team_slug);
                    }
                </script>
                <select onchange="selectTeam(this.options[this.selectedIndex].value);">
                    <option value="{{ MY_TEAMS }}"{% if not request.session.current_team_slug %} selected{% endif %}>Your teams</option>
                    <option value="{{ ALL_TEAMS }}"{% if request.session.current_team_slug == ALL_TEAMS %} selected{% endif %}>All teams</option>
                    <option disabled>&#x2500;&#x2500;&#x2500;&#x2500;&#x2500;&#x2500;&#x2500;&#x2500;&#x2500;&#x2500;&#x2500;&#x2500;</option>
                    {% get_menu "NAV_MENU_TEAM_SELECTOR" as menu %}
                    {% for item in menu %}
                        <option value="{{ item.team_slug }}"{% if item.team_slug == request.session.current_team_slug %} selected{% endif %}>
                            {{ item.name }}
                        </option>
                    {% endfor %}
                </select>
            </div>
        {% endif %}
    </div>
{% endblock %}

skills/templates/skills/empty.html
{% extends "skills/base.html" %}

{% block content %}

<p>At the moment, we do not have anything to show here.</p>

{% endblock %}

skills/templates/skills/home.html
{% extends "skills/base.html" %}

{% block quick_link %}<a href="{% url 'skills:self-assess' %}">Assess yourself…</a>{% endblock %}

{% block content %}

<div class="t-row">
    <div class="t-cell t-header skills-row-header"><em>How to read this?  See <a href="#howto">below</a>.</em></div>
    <div class="t-cell t-header skills-column-header skills-cell-right">← Interest</div>
    <div class="t-cell t-header skills-column-header">Knowledge →</div>
</div>
{% for skill in skills %}
    {% if skill.category_title %}
        <hr>
        <h2>{{ skill.category_title }}</h2>
    {% endif %}
    <div class="t-row">
        <div class="t-cell t-header skills-row-header"><a href="{% url 'skills:skill' skill.skill %}">{{ skill.title }}</a></div>
        <div class="t-cell skills-cell-right">
            {% for level in skill.interest %}
                {% if level %}
                    <div class="t-cell skills-interest-{{ forloop.counter }} skills-cell-narrow">{{ level }}</div>
                {% else %}
                    <div class="t-cell skills-interest skills-cell-narrow">&nbsp;</div>
                {% endif %}
            {% endfor %}
            {% if skill.star_interest %}
                <div class="t-cell skills-cell-narrow">&star;</div>
            {% endif %}
        </div>
        <div class="t-cell skills-cell-left">
            {% for level in skill.knowledge %}
                {% if level %}
                    <div class="t-cell skills-knowledge-{{ forloop.counter }} skills-cell-narrow">{{ level }}</div>
                {% else %}
                    <div class="t-cell skills-cell-narrow">&nbsp;</div>
                {% endif %}
            {% endfor %}
            {% if skill.star_knowledge %}
                <div class="t-cell skills-cell-narrow">&star;</div>
            {% endif %}
        </div>
    </div>
{% endfor %}

<hr>

<h2 id="howto">How to read this page</h2>

<h3>Bricks</h3>

<p>This page shows data aggregated for the entire team.  The main purpose is to give the idea of team capabilities at a glance, without diving into details.</p>

<p>These color bars indicate levels.  The bars are divided into bricks that correspond to levels from 1 to 4, and number in each brick shows how many people rated themselves at that level.  Interest is orange and grows to the left, and knowledge is blue and grows to the right.</p>

<p>Here is the example.</p>

<div class="t-row">
    <div class="t-cell t-header skills-row-header"><u>Django framework</u></div>
    <div class="t-cell skills-cell-right">
        <div class="t-cell skills-interest-1 skills-cell-narrow">2</div>
        <div class="t-cell skills-interest-2 skills-cell-narrow">1</div>
        <div class="t-cell skills-interest skills-cell-narrow">&nbsp;</div>
        <div class="t-cell skills-interest-4 skills-cell-narrow">1</div>
    </div>
    <div class="t-cell skills-cell-left">
        <div class="t-cell skills-knowledge-1 skills-cell-narrow">1</div>
        <div class="t-cell skills-knowledge-2 skills-cell-narrow">2</div>
        <div class="t-cell skills-knowledge-3 skills-cell-narrow">1</div>
        <div class="t-cell skills-cell-narrow">&nbsp;</div>
    </div>
</div>

<p>The orange (left) half is interest; it grows from right to left.  Two people in the team have minimal interest in Django (level 1), one more teammate would like to learn more (level 2), and one person is extremely interested in working with Django (level 4).  Note the gap between levels 2 and 4: nobody rated their interest at level 3.</p>

<p>The blue (right) half is knowledge, and it is read likewise, but from left to right.</p>

<h3>Stars</h3>

<p>Some areas have star marks; these stars mean "notable interest" if appear on the interest side or "good knowledge" otherwise.  The criteria is that the team has minimal number of people at certain levels:</p>

<ul>
    <li><em>Notable interest</em> means that {{ notable_interest_threshold }} people rated their interest at level 4 (the highest).</li>
    <li><em>Good knowledge</em> means that at least {{ high_knowledge_threshold }} people rated their knowledge at level 3, or at least {{ expert_knowledge_threshold }} people rated their knowledge at level 4 (the highest).</li>
</ul>

{% endblock %}

skills/templates/skills/interest-vs-knowledge.html
{% extends "skills/base.html" %}

{% block quick_link %}<a href="{% url 'skills:self-assess' %}">Assess yourself…</a>{% endblock %}

{% block content %}

{% include "skills/snippets/team-members.html" %}

<div class="t-row">
    <div class="t-cell t-header skills-row-header"><em>How to read this?  See <a href="#howto">below</a>.</em></div>
    <div class="t-cell t-header skills-column-header skills-cell-right">← Interest</div>
    <div class="t-cell t-header skills-column-header">Knowledge →</div>
</div>
<hr>
{% for skill in skills %}
    {% if skill.category_title %}
        <h2>{{ skill.category_title }}</h2>
    {% endif %}
    <div class="t-row-nth">
        <div class="t-cell t-header skills-row-header"><a href="{% url 'skills:skill' skill.skill %}">{{ skill.title }}</a></div>
        <div class="t-cell skills-cell-right">
            {% for level in skill.interest %}
                {% if level %}
                    <div class="t-cell skills-interest-{{ forloop.counter }} skills-cell-narrow">{{ level }}</div>
                {% else %}
                    <div class="t-cell skills-interest skills-cell-narrow">&nbsp;</div>
                {% endif %}
            {% endfor %}
            {% if skill.star_interest %}
                <div class="t-cell skills-cell-narrow">&star;</div>
            {% endif %}
        </div>
        <div class="t-cell skills-cell-left">
            {% for level in skill.knowledge %}
                {% if level %}
                    <div class="t-cell skills-knowledge-{{ forloop.counter }} skills-cell-narrow">{{ level }}</div>
                {% else %}
                    <div class="t-cell skills-cell-narrow">&nbsp;</div>
                {% endif %}
            {% endfor %}
            {% if skill.star_knowledge %}
                <div class="t-cell skills-cell-narrow">&star;</div>
            {% endif %}
        </div>
    </div>
{% endfor %}

<hr>

<h2 id="howto">How to read this page</h2>

<h3>Bricks</h3>

<p>This page shows data aggregated for the entire team.  The main purpose is to give the idea of team capabilities at a glance, without diving into details.</p>

<p>These color bars indicate levels.  The bars are divided into bricks that correspond to levels from 1 to 4, and number in each brick shows how many people rated themselves at that level.  Interest is orange and grows to the left, and knowledge is blue and grows to the right.</p>

<p>Here is the example.</p>

<div class="t-row">
    <div class="t-cell t-header skills-row-header"><u>Django framework</u></div>
    <div class="t-cell skills-cell-right">
        <div class="t-cell skills-interest-1 skills-cell-narrow">2</div>
        <div class="t-cell skills-interest-2 skills-cell-narrow">1</div>
        <div class="t-cell skills-interest skills-cell-narrow">&nbsp;</div>
        <div class="t-cell skills-interest-4 skills-cell-narrow">1</div>
    </div>
    <div class="t-cell skills-cell-left">
        <div class="t-cell skills-knowledge-1 skills-cell-narrow">1</div>
        <div class="t-cell skills-knowledge-2 skills-cell-narrow">2</div>
        <div class="t-cell skills-knowledge-3 skills-cell-narrow">1</div>
        <div class="t-cell skills-cell-narrow">&nbsp;</div>
    </div>
</div>

<p>The orange (left) half is interest; it grows from right to left.  Two people in the team have minimal interest in Django (level 1), one more teammate would like to learn more (level 2), and one person is extremely interested in working with Django (level 4).  Note the gap between levels 2 and 4: nobody rated their interest at level 3.</p>

<p>The blue (right) half is knowledge, and it is read likewise, but from left to right.</p>

<h3>Stars</h3>

<p>Some areas have star marks; these stars mean "notable interest" if appear on the interest side or "good knowledge" otherwise.  The criteria is that the team has minimal number of people at certain levels:</p>

<ul>
    <li><em>Notable interest</em> means that {{ notable_interest_threshold }} people rated their interest at level 4 (the highest).</li>
    <li><em>Good knowledge</em> means that at least {{ high_knowledge_threshold }} people rated their knowledge at level 3, or at least {{ expert_knowledge_threshold }} people rated their knowledge at level 4 (the highest).</li>
</ul>

{% endblock %}

skills/templates/skills/person.html
{% extends "skills/base.html" %}

{% block title %}Person: {{ person.login }}{% endblock %}

{% block content %}

<div class="skills-person-category-group-primary">
    <h2>Skills from the teams that {{ person.login }} is member of</h2>

    <div class="t-row">
        <div class="t-cell skills-row-header"></div>
        <div class="t-cell skills-column-header skills-cell-right">← Interest</div>
        <div class="t-cell skills-column-header">Knowledge →</div>
    </div>

{% for skill in skills %}
    {% if skill.separator %}
        {% if not forloop.first %}
    </div>
        {% endif %}
</div>
<div class="skills-person-category-group-other">
    <h2>Skills from other teams</h2>
    {% endif %}
    {% if skill.category_title %}
        {% if not skill.separator and not forloop.first %}
    </div>
        {% endif %}
    <div class="skills-person-category">
        <h3>{{ skill.category_title }}</h3>
    {% endif %}
        <div class="t-row-nth">
            <div class="t-cell skills-row-header"><a href="{% url 'skills:skill' skill.skill %}">{{ skill.title }}</a></div>
            <div class="t-cell skills-cell-right">
                {% if skill.measurement.interest %}
                    <div class="skills-interest-{{ skill.measurement.interest }}">{{ skill.measurement.interest }}</div>
                {% endif %}
            </div>
            <div class="t-cell skills-cell-left">
                {% if skill.measurement.knowledge %}
                    <div class="skills-knowledge-{{ skill.measurement.knowledge }}">{{ skill.measurement.knowledge }}</div>
                {% endif %}
            </div>
        </div>
    {% if forloop.last %}
    </div>
    {% endif %}
{% endfor %}
</div>

<p>{% if latest_assessment %}The latest record for {{ person.login }} is {{ latest_assessment.date }}.{% else %}No records so far.{% endif %}</p>

{% endblock %}