people/urls.py
"""URL configuration of the People application.

This is the main section for the URL map. See also `.root_urls.py`.
"""

from django.http.response import HttpResponseRedirect
from django.urls import path, reverse

from common.auth import get_user_login
from . import views


def home(request):
    return HttpResponseRedirect(reverse('root:person', args=[get_user_login(request)]))


app_name = 'people'
urlpatterns = [
    # Convenience view that redirects to one of meaningful URLs.
    path('', home, name='home'),

    # New contribution form.  The new contribution will be created for the user that is currently logged in.
    path('contribution/new/', views.new_contribution, name='contribution-new'),
    # Shows a single contribution, and allows editing it if it belongs to the user that is currently logged in.
    path('contribution/<int:contribution_id>/', views.render_contribution, name='contribution'),
    # Shows contributions of a person with `login`.
    path('contributions/<str:login>/', views.render_contributions, name='contributions'),

    # Sets the current team (stores it in the session).
    path('<str:login>', views.render_person, name='person'),
    # People picker.
    path('picker/', views.picker, name='picker'),

    # Shows details of a single team.
    path('team/<str:team_slug>/', views.render_team, name='team'),
    # Shows all teams.
    path('teams/', views.render_teams, name='teams'),
]

skills/urls.py
"""skills URL configuration.
"""

from django.urls import path

from . import views

app_name = 'skills'
urlpatterns = [
    # Convenience view that redirects to one of meaningful URLs.
    path('', views.home, name='home'),
    # Sets the current team (stores it in the session).
    # Recognises two special values for 1) showing data for all teams and 2) resetting the view to the teams of the
    # current user.
    path('set-current-team/<str:team_slug>/', views.set_current_team, name='set-current-team'),

    # Team diagrams show data for the teams of the current user.  That requires the user to be in some (at least one)
    # team.  If that is not the case, these views redirect to the team picker.

    # Team diagram of interest versus knowledge.
    path('interest-vs-knowledge/', views.interest_vs_knowledge, name='interest-vs-knowledge'),
    # Team diagram of market demand versus knowledge and interest.
    path('demand-vs-knowledge/', views.demand_vs_knowledge, name='demand-vs-knowledge'),
    # Team portfolio (list of all projects and their focus).
    path('projects/', views.projects, name='projects'),
    # New project form.
    path('project-new/', views.project_new, name='project-new'),
    # Self-assessment form.
    path('self-assess/', views.self_assess, name='self-assess'),

    # Wrapper for the views in the above group.  Shows the team selection form if the current user is not listed in any.
    path('pick-teams/', views.render_pick_teams, name='pick-teams'),

    # Views that do not require the user to be in any team.

    # Shows a single project.  Optionally allows editing it.
    path('project/<int:project_id>/', views.project, name='project'),
    # Shows skills of a single person.
    path('person/<str:login>/', views.render_person, name='person'),
    # Shows data for a single skill: who knows it, and who is interested in it.
    path('skill/<int:skill_id>/', views.render_skill, name='skill'),

    # Team diagram of interest versus knowledge for the particular team, or for all teams.
    path('interest-vs-knowledge/<str:team_slug>/', views.interest_vs_knowledge_for_team,
         name='interest-vs-knowledge-for-team'),
    # Team diagram of market demand versus  knowledge and interest for the particular team.
    path('demand-vs-knowledge/<str:team_slug>/', views.demand_vs_knowledge_for_team,
         name='demand-vs-knowledge-for-team'),
    # Team portfolio (list of all projects and their focus) for the particular team.
    path('projects/<str:team_slug>/', views.projects_for_team, name='projects-for-team'),
]

team/urls.py
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from team import settings

urlpatterns = [
    path('', include('people.root_urls', namespace='root')),
    path('people/', include('people.urls', namespace='people')),
    path('admin/', admin.site.urls),
    path('ballots/', include('ballots.urls', namespace='ballots')),
    path('skills/', include('skills.urls', namespace='skills')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

people/models.py
import datetime
import os
from uuid import uuid4

from django.db import models
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _

from team import settings


def mangle_filename(instance, filename):
    """Generates a UUID-based unique hard-to-guess filename

    :param instance: the DB model that this path is generated for
    :param filename: the "original" filename (normally comes from the uploaded file)
    :return: path to the new location within `MEDIA_ROOT`

    The `instance` may have a `STORAGE_PATH` attribute that will be used as a prefix of the resulting path
    """
    name, ext = os.path.splitext(filename)
    new_path = os.path.join(instance.STORAGE_PATH if hasattr(instance, "STORAGE_PATH") else "",
                            '{}{}'.format(uuid4().hex, ext))
    # UUID is generated based on current time and 14 bit random component as parts, so the collision is not likely.
    # In an unlikely event of the collision, just bail out.
    assert not os.path.exists(new_path)
    return new_path


class Level(models.Model):
    name = models.CharField(max_length=20)
    value = models.IntegerField(unique=True)

    class Meta:
        verbose_name = _('Level')
        verbose_name_plural = _('Levels')

    def __str__(self):
        return self.name


class Person(models.Model):
    # Unique ID of the person in the system.
    login = models.CharField(max_length=30, unique=True)
    # Full name.
    full_name = models.CharField(max_length=100, null=True)
    # Date when this person joined the company.
    join_date = models.DateField(null=True)
    # Level in the company hierarchy.
    level = models.ForeignKey(Level, on_delete=models.PROTECT, null=True)

    teams = models.ManyToManyField('Team', blank=True)

    class Meta:
        verbose_name = _('Person')
        verbose_name_plural = _('People')

    def __str__(self):
        return '{login}@ {name}'.format(login=self.login, name=self.full_name)


class PersonalData(models.Model):
    """
    Extended data about a person.
    """

    STORAGE_PATH = settings.PEOPLE_PERSONAL_DATA_STORAGE

    # Extends the Person model.
    person = models.OneToOneField(Person, on_delete=models.CASCADE)
    # Geographical location in form of a query for the external locator service, like "London, United Kingdom".
    location_query = models.CharField(max_length=100, null=True, blank=True)
    # Timezone database name, like "Europe/Madrid".
    tz_name = models.CharField(max_length=30, default="Etc/UTC")
    # Typical hour of beginning the work.
    work_begin_time = models.TimeField(default=datetime.time(9, 00))
    # Typical hour of ending the work.
    work_end_time = models.TimeField(default=datetime.time(18, 00))
    # Person's avatar.
    avatar = models.ImageField(null=True, blank=True, upload_to=mangle_filename)

    class Meta:
        verbose_name = _('Personal data')
        verbose_name_plural = _('Personal data')

    def __str__(self):
        return str(self.person)


# noinspection PyUnusedLocal
@receiver(models.signals.pre_save, sender=PersonalData)
def delete_old_avatar(sender, instance, **kwargs):
    if not instance.pk:
        return

    try:
        old_avatar = PersonalData.objects.get(pk=instance.pk).avatar
        # old_avatar can be None if it belongs to a new PersonalData that has just been created.
        # It should be deleted IFF it exists AND the new instance differs (that is, either is empty or points to another
        # file).
        if old_avatar and old_avatar.url and old_avatar != instance.avatar:
            old_avatar.delete(save=False)
    except PersonalData.DoesNotExist:
        pass


class Team(models.Model):
    """
    Team inside a company.

    Groups various things within the company, primarily people, but not only people.

    The name may be confusing because it clashes with the name of this entire project.  Sorry.
    """

    slug = models.SlugField(max_length=50, unique=True)
    # Arbitrary name of the team; however, it has some constraints.
    name = models.CharField(max_length=50, unique=True)
    # Arbitrary text describing the team.
    description = models.TextField(default='', blank=True)

    class Meta:
        verbose_name = _('Team')
        verbose_name_plural = _('Teams')

    def __str__(self):
        return self.name

skills/models.py
from django.db import models
from django.db.models import Q
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from people.models import Person, Team

NOTABLE_INTEREST_THRESHOLD = 0.3
EXPERT_KNOWLEDGE_THRESHOLD = 0.2
HIGH_KNOWLEDGE_THRESHOLD = 0.4


class Category(models.Model):
    # Arbitrary name of the category.
    name = models.CharField(max_length=50, unique=True)
    # Which teams this category is defined for.
    teams = models.ManyToManyField(Team, blank=True)

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def __str__(self):
        return self.name


class Skill(models.Model):
    # Arbitrary name of the skill.
    name = models.CharField(max_length=50)
    # A skill belongs to the single Category.
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    # Arbitrary text explaining the skill.
    description = models.TextField(default='', blank=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=('name', 'category'), name='skill_name_unique_in_category'),
        ]
        verbose_name = _('Skill')
        verbose_name_plural = _('Skills')

    def __str__(self):
        return self.name


class PersonAssessment(models.Model):
    """
    Skill assessment of a person.

    Groups a set of Measurements linked to a Person at the certain date, which basically means recording answers to
    a set of questions like 'do you know it? would you like to know it?' asked to the person as a block (e.g., in form
    of a survey).
    """

    # When this assessment has been recorded.
    date = models.DateField()
    # Who is this assessment recorded for.
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    # Whether this is the most recent assessment.  Simplifies the logic of loading the team profile.
    latest = models.BooleanField(default=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=('date', 'person'), name='one_assessment_per_day'),
            models.UniqueConstraint(fields=['person'], condition=Q(latest=True), name='one_latest_per_person')
        ]
        verbose_name = _('Assessment')
        verbose_name_plural = _('Assessments')

    def __str__(self):
        return _('{person} at {date}').format(person=self.person, date=self.date)


class Measurement(models.Model):
    """
    Records one pair of knowledge and interest of a person in a particular area.

    Represents a single answer to a question: "Regarding skill X, how good are you in it, and how much would you like to
    use it in your work?"  The answer consists of two values: the perceived level of knowledge and the desire to use or
    learn that skill.  Several measurements for different skills are grouped in an instance of the PersonAssessment
    model.
    """
    KNOWLEDGE_NONE = 0
    KNOWLEDGE_LOW = 1
    KNOWLEDGE_MEDIUM = 2
    KNOWLEDGE_HIGH = 3
    KNOWLEDGE_EXPERT = 4
    KNOWLEDGE_CHOICES = (
        (KNOWLEDGE_NONE, _('No knowledge')),
        (KNOWLEDGE_LOW, _('Touched it while doing unrelated things')),
        (KNOWLEDGE_MEDIUM, _('Did minor things there')),
        (KNOWLEDGE_HIGH, _('Did major things there')),
        (KNOWLEDGE_EXPERT, _('I am expert in this area')),
    )

    INTEREST_NONE = 0
    INTEREST_LOW = 1
    INTEREST_MEDIUM = 2
    INTEREST_HIGH = 3
    INTEREST_EXTREME = 4
    INTEREST_CHOICES = (
        (INTEREST_NONE, _('No interest')),
        (INTEREST_LOW, _('I would not mind working in this area')),
        (INTEREST_MEDIUM, _('I would like to work in this area')),
        (INTEREST_HIGH, _('I really want to work in this area')),
        (INTEREST_EXTREME, _('This is one of my favourite areas')),
    )

    assessment = models.ForeignKey(PersonAssessment, on_delete=models.CASCADE)
    skill = models.ForeignKey(Skill, on_delete=models.CASCADE)
    knowledge = models.IntegerField(choices=KNOWLEDGE_CHOICES, default=KNOWLEDGE_NONE)
    interest = models.IntegerField(choices=INTEREST_CHOICES, default=INTEREST_NONE)


class Project(models.Model):
    """A project that has been evaluated.  Not necessarily the one that the team works on.
    """

    # Project name.
    name = models.CharField(max_length=50, verbose_name=_('Name'), unique=True)
    # Arbitrary text explaining the project.
    description = models.TextField(default='', verbose_name=_('Description'))
    # Date of the most recent evaluation.
    date = models.DateField(verbose_name=_('Last assessment'))
    # Whether this project has been worked on by the team.
    active = models.BooleanField(default=False, verbose_name=_('The team is/was working on it'))
    # Which teams this project is driven by.
    teams = models.ManyToManyField(Team, blank=True)

    class Meta:
        verbose_name = _('Project')
        verbose_name_plural = _('Projects')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.date = timezone.now()
        super().save(*args, **kwargs)


class ProjectFocusRecord(models.Model):
    """Marks one skill that the project focuses on.
    """
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    skill = models.ForeignKey(Skill, on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=('project', 'skill'), name='unique_skill_in_project')
        ]
        verbose_name = _('Project focus record')
        verbose_name_plural = _('Project focus records')

    def __str__(self):
        return _('{project} → {skill}').format(project=self.project.name, skill=self.skill.name)

people/forms.py
from django import forms

from people.models import PersonalData
from skills.models import Contribution


class ContributionForm(forms.ModelForm):
    """Allows to edit personal contribution.

    Used by the people.add_or_edit_contribution view.
    """
    class Meta:
        model = Contribution
        fields = ('project', 'description')


class PersonalDataForm(forms.ModelForm):
    """Allows to edit personal details.

    Used by the people.render_person view.
    """
    class Meta:
        model = PersonalData
        fields = ('location_query', 'tz_name', 'work_begin_time', 'work_end_time')


class SearchForm(forms.Form):
    """Captures the login of a person to show.

    Used by the people.render_person view.
    """
    login = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Type to search'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        fields = ('login',)

people/templates/people/contributions.html
{% extends "people/base.html" %}
{% load i18n %}{% load markdownify %}

{% block title %}
    {% if can_edit %}
        {% translate "My contributions" %}
    {% else %}
        {% url 'root:person' person.login as person_url %}
        {% blocktranslate %}<a href="{{ person_url }}">{{ person }}</a>'s contributions{% endblocktranslate %}
    {% endif %}
{% endblock %}

{% block quick_link %}
    {% if can_edit %}
        <a href="{% url 'people:contribution-new' %}">Add new…</a>
    {% endif %}
{% endblock %}

{% block content %}

{% for contribution in contributions %}
    <div class="t-row-nth">
        <div class="t-cell people-person-contributions-project-cell">
            <a href="{% url 'skills:project' contribution.project.id %}">{{ contribution.project }}</a>
        </div>
        <div class="t-cell people-person-contributions-details-cell">
            <div class="t-row">
                <div class="t-cell">
                    {{ contribution.description|markdownify }}
                </div>
            </div>
            <div class="t-row">
                <div class="t-cell">
                    {% for skill in contribution.skills.all %}
                        <span class="people-person-contribution-project-skill">{{ skill.name }}</span>
                    {% endfor %}
                </div>
            </div>
            <div class="t-row">
                <div class="t-cell">
                    <a href="{% url 'people:contribution' contribution.id %}">Edit…</a>
                </div>
            </div>
        </div>
    </div>
{% endfor %}

{% endblock %}

people/templates/people/person.html
{% extends "people/base.html" %}
{% load menu_generator %}{% load static %}

{% block title %}{{ person | default_if_none:"Person not found" }}{% endblock %}

{% block content %}

<form method="post" autocomplete="off" id="id_search_form">
    {% csrf_token %}

    <div class="people-autocomplete">{{ search_form.login }}</div>
</form>

{% if person %}
<div class="t-row">
    <div class="t-cell people-person-block-photo">
        {% if personal_data.avatar %}
            <img src="{{ personal_data.avatar.url }}" width="200" height="200">
        {% else %}
            <img src="{% static 'people/stub-avatar.png' %}" width="200" height="200">
        {% endif %}
    </div>
    <div class="t-cell people-person-block-data">
        <div class="t-row">
            <div class="t-cell people-person-block-company-data">
                <div class="t-row">
                    <div class="t-cell t-header">
                        Company data
                    </div>
                </div>

                <div class="t-row">
                    <div class="t-cell">Joined:</div>
                    <div class="t-cell">{{ person.join_date }}</div>
                </div>

                <div class="t-row">
                    <div class="t-cell">Level:</div>
                    <div class="t-cell">{{ person.level }}</div>
                </div>

                <div class="t-row">
                    <div class="t-cell">Teams:</div>
                    <div class="t-cell">{% for team in person.teams.all %}<a href="{% url 'people:team' team.slug %}">{{ team }}</a>{% endfor %}</div>
                </div>
            </div>

            <div class="t-cell people-person-block-personal-data">
                <div class="t-row">
                    <div class="t-cell t-header">
                        Personal data
                    </div>
                    {% if can_edit %}
                        <div class="t-cell"><button id="toggle-personal-data-form" value="edit">&#9997;&#65039; Edit️</button></div>
                    {% endif %}
                </div>

                <div id="personal-data-view">
                    <form method="post" autocomplete="off" id="personal-data-form">
                        {% csrf_token %}
                        <div class="t-row people-personal-data">
                            <div class="t-cell people-personal-data-label">Location:</div>
                            <div class="t-cell people-personal-data-view">{{ personal_data.location_query | default_if_none:"&mdash;" }}</div>
                            <div class="t-cell people-personal-data-field" style="display: none">{{ personal_data_form.location_query }}</div>
                        </div>

                        <div class="t-row people-personal-data">
                            <div class="t-cell people-personal-data-label">Time zone:</div>
                            <div class="t-cell people-personal-data-view">{{ personal_data.tz_name }}</div>
                            <div class="t-cell people-personal-data-field" style="display: none">{{ personal_data_form.tz_name }}</div>
                        </div>

                        <div class="t-row people-personal-data">
                            <div class="t-cell people-personal-data-label">Working hours:</div>
                            <div class="t-cell people-personal-data-view">
                                <div class="t-row">
                                    <div class="t-cell people-small-field">{{ personal_data.work_begin_time }}</div>
                                    <div class="t-cell">&mdash;</div>
                                    <div class="t-cell people-small-field">{{ personal_data.work_end_time }}</div>
                                </div>
                            </div>
                            <div class="t-cell people-personal-data-field" style="display: none">
                                <div class="t-row">
                                    <div class="t-cell people-small-field">{{ personal_data_form.work_begin_time }}</div>
                                    <div class="t-cell">&mdash;</div>
                                    <div class="t-cell people-small-field">{{ personal_data_form.work_end_time }}</div>
                                </div>
                            </div>
                        </div>

                        <div class="t-row people-personal-data">
                            <div class="t-cell-right people-personal-data-view"></div>
                            <div class="t-cell-right people-personal-data-field" style="display: none"><button type="submit">Save</button></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="t-row">
            {% if inventory %}
                <div class="t-cell people-person-inventory">
                    <div class="t-row"><div class="t-cell t-header">Inventory</div></div>
                    {% for device in inventory %}
                        <div class="t-row"><div class="t-cell">{{ device.model.type }}: {{ device.model }}</div></div>
                    {% endfor %}
                </div>
            {% endif %}
            {% if contributions %}
                <div class="t-cell people-person-contributions">
                    <div class="t-row">
                        <div class="t-cell t-header">Contributions</div>
                        {% if can_edit %}
                            <div class="t-cell right"><a href="{% url 'people:contributions' person.login %}">Full details/Edit</a></div>
                        {% else %}
                            <div class="t-cell right"><a href="{% url 'people:contributions' person.login %}">Full details…</a></div>
                        {% endif %}
                    </div>
                    {% for contribution in contributions %}
                        <div class="t-row-nth">
                            <div class="t-cell people-person-contributions-project-cell">{{ contribution.project }}</div>
                            <div class="t-cell people-person-contributions-details-cell">
                                <div class="t-row">
                                    <div class="t-cell">{{ contribution.description }}</div>
                                </div>
                                <div class="t-row">
                                    <div class="t-cell">
                                        {% for skill in contribution.skills.all %}
                                            <span class="people-person-contribution-project-skill">{{ skill.name }}</span>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% else %}
<p>Use the search bar to find people.</p>
{% endif %}

<script language="JavaScript">
    var peopleData = [
        {% for person in people %}
        { "login": "{{ person.login }}", "name": "{{ person.full_name }}" },{% endfor %}
    ];

    // Autocompletion input.  Inspired by https://www.w3schools.com/howto/howto_js_autocomplete.asp
    function setAutocomplete(textInput, data) {
        var currentFocus = -1;

        // Looks for matches of |value| in data[index], which is a dictionary that has login and name fields.
        // Login and name are matched using different rules (see comments in the code below).
        // If there are matches, returns a user-friendly string that shows the match, otherwise returns false.
        function findMatches(value, index) {
            var login = data[index]["login"];
            var name = data[index]["name"];

            // Login matches if it begins with the value.
            var loginMatch = false;
            if (value.toLowerCase() == login.substr(0, value.length).toLowerCase())
                loginMatch = "<strong>" + login.substr(0, value.length) + "</strong>" + login.substr(value.length);

            // Name matches if it contains the value.
            var nameMatch = false;
            var name_found_index = name.toLowerCase().search(value.toLowerCase());
            if (name_found_index >= 0) {
                nameMatch = name.substr(0, name_found_index)
                                + "<strong>"
                                + name.substr(name_found_index, value.length)
                                + "</strong>"
                                + name.substr(name_found_index + value.length);
            }

            if (!loginMatch && !nameMatch)
                return false;

            return (loginMatch ? loginMatch : login) + "@ " + (nameMatch ? nameMatch : name);
        }

        textInput.addEventListener("input", function(e) {
            var value = this.value;
            // Close any already open lists of autocompleted values.
            closeAllLists();

            if (!value)
                return false;

            currentFocus = -1;

            const dropDownList = document.createElement("DIV");
            dropDownList.setAttribute("id", this.id + "autocomplete-list");
            dropDownList.setAttribute("class", "people-autocomplete-items");

            // Append the DIV element as a child of the autocomplete container:
            this.parentNode.appendChild(dropDownList);
            for (var i = 0; i < data.length; i++) {
                match = findMatches(value, i);
                if (!match)
                    continue;

                const listItem = document.createElement("DIV");
                listItem.innerHTML = match;
                listItem.innerHTML += "<input type='hidden' value='" + data[i]["login"] + "'>";

                // On click, take the value stored in the item and submit the form.
                listItem.addEventListener("click", function(e) {
                    textInput.value = this.getElementsByTagName("input")[0].value;
                    closeAllLists();
                    document.getElementById("id_search_form").submit();
                });
                dropDownList.appendChild(listItem);
            }
        });

        textInput.addEventListener("keydown", function(e) {
            const dropDownList = document.getElementById(this.id + "autocomplete-list");
            if (!dropDownList)
                return;
            const items = dropDownList.getElementsByTagName("div");
            if (items.length == 0)
                return;

            switch (e.key) {
            case "ArrowDown":
                ++currentFocus;
                updateActive(items);
                e.preventDefault();
                break;
            case "ArrowUp":  // Up.
                --currentFocus;
                updateActive(items);
                e.preventDefault();
                break;
            case "Enter":  // Enter.
                if (currentFocus > -1) {
                    items[currentFocus].click();
                } else {
                    var loginExists = false;
                    for (i = 0; i < data.length; i++) {
                        if (textInput.value == data[i]["login"]) {
                            loginExists = true;
                            break;
                        }
                    }
                    if (!loginExists)
                        e.preventDefault();
                }
                break;
            }
        });

        function updateActive(items) {
            if (currentFocus >= items.length)
                currentFocus = 0;
            if (currentFocus < 0)
                currentFocus = (items.length - 1);

            for (var i = 0; i < items.length; i++) {
                if (i == currentFocus)
                    items[i].classList.add("people-autocomplete-active");
                else
                    items[i].classList.remove("people-autocomplete-active");
            }
        }

        // Closes all autocomplete lists in the document, except the one passed as an argument.
        function closeAllLists(exceptThis) {
            var autocompleteLists = document.getElementsByClassName("people-autocomplete-items");
            for (var i = 0; i < autocompleteLists.length; i++) {
                if (autocompleteLists[i] != exceptThis && exceptThis != textInput)
                    autocompleteLists[i].parentNode.removeChild(autocompleteLists[i]);
            }
        }

        document.addEventListener("click", function (e) {
            closeAllLists(e.target);
        });
    }

    setAutocomplete(document.getElementById("id_login"), peopleData);
    document.getElementById("id_login").focus();

{% if can_edit %}
    function toggleEditForm(e) {
        var personalDataRows = document.getElementsByClassName("people-personal-data");
        for (var i = 0; i < personalDataRows.length; i++) {
            const view = personalDataRows[i].getElementsByClassName("people-personal-data-view")[0];
            const field = personalDataRows[i].getElementsByClassName("people-personal-data-field")[0];
            [view.style.display, field.style.display] = [field.style.display, view.style.display];
        }

        var toggleButton = e.target;
        if (toggleButton.value === "edit") {
            toggleButton.innerHTML = "&#128683; Cancel";
            toggleButton.value = "cancel"
        } else {
            toggleButton.innerHTML = "&#9997;&#65039; Edit";
            toggleButton.value = "edit"
            document.getElementById("personal-data-form").reset();
        }
    }

    document.getElementById("toggle-personal-data-form").addEventListener("click", toggleEditForm);
{% endif %}
</script>

{% endblock %}

people/templates/people/team.html
{% extends "people/base.html" %}
{% load markdownify %}

{% block title %}{{ team | default_if_none:"Team not found" }}{% endblock %}

{% block content %}

{{ team.description|markdownify }}

<h2>Members</h2>

<ul>
{% for person in team.person_set.all %}
    <li><a href="{% url 'root:person' person.login %}">{{ person }}</a></li>
{% endfor %}
</ul>

<h2>Projects</h2>

<ul>
{% for project in team.project_set.all %}
    <li><a href="{% url 'skills:project' project.id %}">{{ project }}</a></li>
{% endfor %}
</ul>

{% endblock %}